### PR TITLE
Drop `dask` entry point

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Attempting to address the issue outlined by comment ( https://github.com/conda-forge/distributed-feedstock/pull/226#issuecomment-1286497407 ).

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by jakirkham** [comment]
Given we are still seeing issues with the `dask` entry point ( https://github.com/conda-forge/distributed-feedstock/pull/226#issuecomment-1286497407 ), proposing we drop it.

Thoughts @jrbourbeau? 🙂

**Review by jrbourbeau — COMMENTED** [review]
Thanks @jakirkham. I'm (unfortunately) able to reproduce. I'm not sure how dropping the `dask` entrypoint will help. Based on the conda-forge docs, I thought we needed to specify `console_script` entrypoints in the recipe.

From the [docs on `noarach` Python packages](https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python) it says 

> Only console_scripts entry points have to be listed in meta.yaml. Other entry points do not conflict with noarch and therefore do not require extra treatment.

We've included the `dask` `console_scripts` entrypoint here. I'm confused why the `distributed` entrypoints behind `dask scheduler`, etc. aren't working since they're [not defined via `console_scipts`](https://github.com/dask/distributed/blob/6afce9cce6ab402fa44736dc57b39fbc355b4c11/setup.py#L70-L73)

**Comment by jakirkham** [comment]
Charles observed we have the wrong entry point path. PR ( https://github.com/conda-forge/dask-core-feedstock/pull/146 ) addresses this. Though there is a question about whether we need to tweak it further

**Comment by jakirkham** [comment]
Superseded by PR ( https://github.com/conda-forge/dask-core-feedstock/pull/146 )

**Pull request closed without merging**
